### ISSUE TITLE
Allow deep linking for urls with slug of courses not yet in local DB

### ISSUE THREAD

**Issue by janrenz** [openHPI/xikolo-ios#273]
user klicks /courses/new_course somewhere, app delegates takes care but course is not yet available in CoreData

**Comment by bjrne** [comment]
Is this closed for some reason or fixed?

**Comment by janrenz** [comment]
Fixed on Server. may require reload of app.

**Comment by mathebox** [comment]
Nope. That was not fixed on the server but here: https://github.com/openHPI/xikolo-ios/blob/dev/xikolo-ios/AppNavigator.swift#L60-L66

**Comment by janrenz** [comment]
You are right, I mixed this with today’s changes
